SELECT * FROM negocio.PRODUCTO;

/* TRAER EL ID Y NOMBRE DEL PRODUCTO Y SU PROVEEDOR QUE LE CORRESPONDE USAR JOIN Y ASIGNARLE UN ALIAS A LAS TABLAS */

SELECT P.ID_PRO AS ID, P.NOMBRE_P AS PRODUCTO, PR.NOMBRE_PRO AS PROVEEDOR 
FROM PRODUCTO P INNER JOIN PROVEEDOR PR
	ON PR.ID_PROV=P.ID_PROV;


/* TRAE EL NOMBRE DE CADA PRODUCTO Y EL TOTAL DEL PRECIO TENIENDO EN CUENTA LA CANTIDAD DEL STOCK QUE TIENEN */

SELECT NOMBRE_P AS PRODUCTO, (PRECIO*CANTIDAD) as Total 
FROM PRODUCTO;

SELECT NOMBRE_P, precio, cantidad, (PRECIO*CANTIDAD) as Total 
FROM PRODUCTO;

/* 1.-DE LA TABLA DE VENTAS TRAER EL NOMBRE DEL PRODUCTO,CLIENTE Y EMPLEADO Y EL PRECIO DEL PRODUCTO. */

SELECT V.ID_V AS VENTA, V.ID_E AS ID, E.NOMBRE_E AS EMPLEADO, V.ID_C AS ID, C.NOMBRE_C AS CLIENTE, V.ID_PRO AS ID, P.NOMBRE_P AS PRODUCTO, P.PRECIO AS PRECIO 
FROM VENTA V
INNER JOIN EMPLEADO E
   ON E.ID_E=V.ID_E
INNER JOIN CLIENTE C
   ON C.ID_C=V.ID_C
INNER JOIN PRODUCTO P
   ON P.ID_PRO=V.ID_PRO;

/*   2.- SUMA EL TOTAL DE LOS PRODUCTOS COMPRADOS (LA SALIDA SIN PRODUCTOS REPETIDOS) Y QUE DE EL TOTAL */

SELECT  V.ID_PRO AS ID, P.NOMBRE_P AS PRODUCTO, P.PRECIO, COUNT(*) AS VENTAS, (P.PRECIO*COUNT(*)) AS TOTAL
FROM VENTA V
INNER JOIN PRODUCTO P
   ON P.ID_PRO=V.ID_PRO
GROUP BY V.ID_PRO;



